.github/workflows/website.yaml
Create separate build and deploy jobs so that environments can be used appropriately.
=> ci: Separate build/deploy jobs

src/css/custom.css
=> chore: Update CSS for mobile

src/css/custom.css
Make button shrink to 90% vs. 10% its size.
=> chore: Adjust button transform

docusaurus.config.ts, src/css/custom.css
chore: Update title size
chore: Update css for input
=> chore: Update email input CSS

.github/workflows/website.yaml, docusaurus.config.ts, src/pages/index.tsx
=> chore: Update title

.github/workflows/build.yaml, .github/workflows/deploy.yaml
Makes management of both easier without the need for if conditions.
=> ci: Separate build and deploy workflows

static/robots.txt
=> chore: Add `robots.txt`

docs/intro.md, src/components/LandingPage/LandingPage.tsx, src/css/custom.css
chore: Update and add codegen category to landing page
chore: Update codegen category
chore: updated overview in docs
chore: Add client features section
chore: Update footer top border
chore: Make code font size bigger
=> chore: Update client categories and increase font size of code snippet

src/css/custom.css
Ensure good looking code at 375px width screens
=> chore: Fix code for small form factors

babel.config.js
Fixes https://celest.sentry.io/issues/4723127744/
=> fix: Cannot destructure property 'scrollWidth' of 'c.current' as it is null.

docusaurus.config.ts, package.json, pnpm-lock.yaml, src/common/analytics.ts
Currently, both GA and PostHog will run until PostHog has been properly vetted.
=> feat: Add PostHog for analytics

src/components/LandingPage/EmailForm.tsx
- Fixed events to follow a naming pattern that detects success VS failure.
- Updated an incorrect firing of the "Too many sign-ups" event.
=> chore(analytics): Fix analytics events for Posthog

src/components/LandingPage/LandingPage.tsx
Runs prettier on `LandingPage.tsx`
=> chore: Format landing page file

docs/cli-commands-reference.md, docs/functions/creating-functions.md, docs/functions/data-types.md, docs/functions/env-variables.md, docs/functions/exceptions.md, docs/functions/logging.md, docs/get-started.md, docs/overview.md, docusaurus.config.ts, package.json, pnpm-lock.yaml
- Updates code snippets to be consistent with new types/practices
- Refines language
=> chore(docs): Update code snippets

src/pages/download.tsx
=> chore(docs): Update docs for download page for local iterations release

docs/functions/http-requests.md, docs/functions/packages.md, docs/functions/testing.md
Clean up remaining code snippets and references.
=> chore(docs): Clean up

src/pages/download.tsx
=> chore(download): Hide button on Windows

docusaurus.config.ts
Remove LinkedIn and YouTube links from navbar
=> chore: Clean up navbar

docs/functions/creating-functions.md, src/components/LandingPage/LandingPage.tsx
Update code snippet title of the homepage widget
=> chore(docs): Update code snippet title

docusaurus.config.ts, src/pages/download.tsx
chore(docs): Update Windows download links for CLI
updated windows links, added events for auto detection
=> feat: Release local iteration CLI

blog/2024-01-22-local-iterations-mvp/index.md
=> chore(blog): Remove video mention

blog/2024-01-22-local-iterations-mvp/index.md, docs/overview.md, src/css/custom.css, src/pages/about-us.md
And update styles to share with about-us page videos.
=> chore: Add links to our intro YouTube video

docs/cli-commands-reference.md, docs/functions/creating-functions.md, docs/get-started.md
=> chore(docs): Update docs based on feedback

docs/cli-commands-reference.md
Add CLI upgrade command to docs.
=> chore(docs): Add upgrade command to docs.

blog/2024-01-22-local-iterations-mvp/index.md, docs/overview.md, docusaurus.config.ts, src/pages/about-us.md
Update Celest descriptions across docs.
=> chore(docs): Update Celest descriptions across docs.

blog/2024-01-22-local-iterations-mvp/index.md, docs/overview.md, docusaurus.config.ts, src/pages/about-us.md
Update description of Celest to BaaS.
=> chore(docs): Update BaaS description for Celest.

docusaurus.config.ts, package.json, pnpm-lock.yaml, src/components/LandingPage/LandingPage.tsx, src/components/LandingPage/calendar.tsx, src/css/custom.css
Add cal.com embed to landing page.
=> chore(docs): Add cal invite embed to landing page.

docs/functions/data-types.md, docs/functions/env-variables.md, docs/get-started.md
Update docs based on customer feedback.
=> chore(docs): Update docs based on customer feedback.

docusaurus.config.ts
Update edit link URLs to point to the Celest website repo.
=> chore(docs): Update the edit link URLs.

docusaurus.config.ts
=> chore(docs): Remove unnecessary comments.

docusaurus.config.ts
To help make clear that Teo, Inc. and Celest are one in the same.
=> chore: Add Celest to footer

docs/functions/introduction.md
=> chore(docs): Typo in introduction

package.json, pnpm-lock.yaml
=> chore: Update dependencies

src/components/LandingPage/LandingPage.tsx, src/components/LandingPage/calendar.tsx
=> chore: Update calendar

src/components/LandingPage/LandingPage.tsx
Optimizing per https://web.dev/patterns/web-vitals-patterns/video/video
=> chore: Set width/height on video

docusaurus.config.ts, src/components/LandingPage/LandingPage.tsx, src/theme/Navbar/Logo/index.tsx
From Lighthouse recommendations
=> chore: Add width/height to images

docusaurus.config.ts, src/css/custom.css
Follows recommendations from:
- https://developer.chrome.com/docs/lighthouse/performance/font-display/
- https://keithgreer.dev/lighthouse-google-fonts/
=> chore: Inline font loading

src/components/LandingPage/LandingPage.tsx
=> chore: Remove video poster

.github/workflows/build.yaml, .github/workflows/deploy.yaml, .github/workflows/deploy_preview.yaml, tool/.gitignore, tool/analysis_options.yaml, tool/create_preview_url.dart, tool/pubspec.yaml
Finishes support for preview environments.
- Adds URL Map and DNS updates to workflow
- Uses PR number for URL, e.g. `https://pr-100.preview.celest.dev`
=> ci: Finish preview environments

src/components/LandingPage/Download.tsx, src/css/custom.css, tool/create_preview_url.dart
So that mobile layouts are nicer
=> chore: Improve platform detection

src/css/custom.css
=> fix: Header height

components/landing/PricingTable.tsx
Fixes layout issues with pricing table
=> fix: Pricing layout

pages/docs/functions/data-types.mdx
Part of https://github.com/celest-dev/celest/issues/54
=> chore(docs): Improve data types callout

next.config.mjs, public/.well-known/com.apple.remotemanagement
=> chore: Add remote management config

next.config.mjs
This reverts commit e5910a460e35f6cc9dcf9249e90206d25463777c.
=> Revert "chore: Rewrite remote management config (#140)"

next.config.mjs, public/.well-known/com.apple.remotemanagement
This reverts commit 4284d76d26701090243b9422ddbcf6a627fa8cd5.
=> Revert "chore: Add remote management config (#139)"

pages/docs/data.mdx
_This was added today and is much more readable_
In Drift 2.21
=> Use updated syntax

components/DownloadButton.tsx, components/landing/Hero.tsx, pages/docs/get-started.mdx, pages/index.mdx
Replace download instructions with the new `dart pub global` command.
=> chore: Replace download instructions
